name: tfsec
permissions: write-all

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  call-workflow-tfsec:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec.yml@master
    secrets: inherit
    with:
      working_directory: './_example'